function Constants() {
  this.opcodes = [
    /* 0x00 */ {'instruction': 'BRK', 'cycle': 7, 'addressing': 'IMPLIED'},
    /* 0x01 */ {'instruction': 'ORA', 'cycle': 6, 'addressing': 'INDEXED_INDIRECT_X'},
    /* 0x02 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x03 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x04 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x05 */ {'instruction': 'ORA', 'cycle': 3, 'addressing': 'ZERO_PAGE'},
    /* 0x06 */ {'instruction': 'ASL', 'cycle': 5, 'addressing': 'ZERO_PAGE'},
    /* 0x07 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0x08 */ {'instruction': 'PHP', 'cycle': 3, 'addressing': 'IMPLIED'},
    /* 0x09 */ {'instruction': 'ORA', 'cycle': 2, 'addressing': 'IMMEDIATE'},
    /* 0x0A */ {'instruction': 'ASL', 'cycle': 2, 'addressing': 'ACCUMULATOR'},
    /* 0x0B */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x0C */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x0D */ {'instruction': 'ORA', 'cycle': 4, 'addressing': 'ABSOLUTE'},
    /* 0x0E */ {'instruction': 'ASL', 'cycle': 6, 'addressing': 'ABSOLUTE'},
    /* 0x0F */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0x10 */ {'instruction': 'BPL', 'cycle': 2, 'addressing': 'RELATIVE'},
    /* 0x11 */ {'instruction': 'ORA', 'cycle': 5, 'addressing': 'INDEXED_INDIRECT_Y'},
    /* 0x12 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x13 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x14 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x15 */ {'instruction': 'ORA', 'cycle': 4, 'addressing': 'INDEXED_ZERO_PAGE_X'},
    /* 0x16 */ {'instruction': 'ASL', 'cycle': 6, 'addressing': 'INDEXED_ZERO_PAGE_X'},
    /* 0x17 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0x18 */ {'instruction': 'CLC', 'cycle': 2, 'addressing': 'IMPLIED'},
    /* 0x19 */ {'instruction': 'ORA', 'cycle': 4, 'addressing': 'INDEXED_ABSOLUTE_Y'},
    /* 0x1A */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x1B */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x1C */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x1D */ {'instruction': 'ORA', 'cycle': 4, 'addressing': 'INDEXED_ABSOLUTE_X'},
    /* 0x1E */ {'instruction': 'ASL', 'cycle': 7, 'addressing': 'INDEXED_ABSOLUTE_X'},
    /* 0x1F */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0x20 */ {'instruction': 'JSR', 'cycle': 0, 'addressing': 'ABSOLUTE'},
    /* 0x21 */ {'instruction': 'AND', 'cycle': 6, 'addressing': 'INDEXED_INDIRECT_X'},
    /* 0x22 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x23 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x24 */ {'instruction': 'BIT', 'cycle': 3, 'addressing': 'ZERO_PAGE'},
    /* 0x25 */ {'instruction': 'AND', 'cycle': 3, 'addressing': 'ZERO_PAGE'},
    /* 0x26 */ {'instruction': 'ROL', 'cycle': 5, 'addressing': 'ZERO_PAGE'},
    /* 0x27 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0x28 */ {'instruction': 'PLP', 'cycle': 4, 'addressing': 'IMPLIED'},
    /* 0x29 */ {'instruction': 'AND', 'cycle': 2, 'addressing': 'IMMEDIATE'},
    /* 0x2A */ {'instruction': 'ROL', 'cycle': 2, 'addressing': 'ACCUMULATOR'},
    /* 0x2B */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x2C */ {'instruction': 'BIT', 'cycle': 4, 'addressing': 'ABSOLUTE'},
    /* 0x2D */ {'instruction': 'AND', 'cycle': 4, 'addressing': 'ABSOLUTE'},
    /* 0x2E */ {'instruction': 'ROL', 'cycle': 6, 'addressing': 'ABSOLUTE'},
    /* 0x2F */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0x30 */ {'instruction': 'BMI', 'cycle': 2, 'addressing': 'RELATIVE'},
    /* 0x31 */ {'instruction': 'AND', 'cycle': 5, 'addressing': 'INDEXED_INDIRECT_Y'},
    /* 0x32 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x33 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x34 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x35 */ {'instruction': 'AND', 'cycle': 4, 'addressing': 'INDEXED_ZERO_PAGE_X'},
    /* 0x36 */ {'instruction': 'ROL', 'cycle': 6, 'addressing': 'INDEXED_ZERO_PAGE_X'},
    /* 0x37 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0x38 */ {'instruction': 'SEC', 'cycle': 2, 'addressing': 'IMPLIED'},
    /* 0x39 */ {'instruction': 'AND', 'cycle': 4, 'addressing': 'INDEXED_ABSOLUTE_Y'},
    /* 0x3A */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x3B */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x3C */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x3D */ {'instruction': 'AND', 'cycle': 4, 'addressing': 'INDEXED_ABSOLUTE_X'},
    /* 0x3E */ {'instruction': 'ROL', 'cycle': 7, 'addressing': 'INDEXED_ABSOLUTE_X'},
    /* 0x3F */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0x40 */ {'instruction': 'RTI', 'cycle': 6, 'addressing': 'IMPLIED'},
    /* 0x41 */ {'instruction': 'EOR', 'cycle': 6, 'addressing': 'INDEXED_INDIRECT_X'},
    /* 0x42 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x43 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x44 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x45 */ {'instruction': 'EOR', 'cycle': 3, 'addressing': 'ZERO_PAGE'},
    /* 0x46 */ {'instruction': 'LSR', 'cycle': 5, 'addressing': 'ZERO_PAGE'},
    /* 0x47 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0x48 */ {'instruction': 'PHA', 'cycle': 3, 'addressing': 'IMPLIED'},
    /* 0x49 */ {'instruction': 'EOR', 'cycle': 2, 'addressing': 'IMMEDIATE'},
    /* 0x4A */ {'instruction': 'LSR', 'cycle': 2, 'addressing': 'ACCUMULATOR'},
    /* 0x4B */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x4C */ {'instruction': 'JMP', 'cycle': 0, 'addressing': 'ABSOLUTE'},
    /* 0x4D */ {'instruction': 'EOR', 'cycle': 4, 'addressing': 'ABSOLUTE'},
    /* 0x4E */ {'instruction': 'LSR', 'cycle': 6, 'addressing': 'ABSOLUTE'},
    /* 0x4F */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0x50 */ {'instruction': 'BVC', 'cycle': 2, 'addressing': 'RELATIVE'},
    /* 0x51 */ {'instruction': 'EOR', 'cycle': 5, 'addressing': 'INDEXED_INDIRECT_Y'},
    /* 0x52 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x53 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x54 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x55 */ {'instruction': 'EOR', 'cycle': 4, 'addressing': 'INDEXED_ZERO_PAGE_X'},
    /* 0x56 */ {'instruction': 'LSR', 'cycle': 6, 'addressing': 'INDEXED_ZERO_PAGE_X'},
    /* 0x57 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0x58 */ {'instruction': 'CLI', 'cycle': 2, 'addressing': 'IMPLIED'},
    /* 0x59 */ {'instruction': 'EOR', 'cycle': 4, 'addressing': 'INDEXED_ABSOLUTE_Y'},
    /* 0x5A */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x5B */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x5C */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x5D */ {'instruction': 'EOR', 'cycle': 4, 'addressing': 'INDEXED_ABSOLUTE_X'},
    /* 0x5E */ {'instruction': 'LSR', 'cycle': 7, 'addressing': 'INDEXED_ABSOLUTE_X'},
    /* 0x5F */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0x60 */ {'instruction': 'RTS', 'cycle': 6, 'addressing': 'IMPLIED'},
    /* 0x61 */ {'instruction': 'ADC', 'cycle': 6, 'addressing': 'INDEXED_INDIRECT_X'},
    /* 0x62 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x63 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x64 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x65 */ {'instruction': 'ADC', 'cycle': 3, 'addressing': 'ZERO_PAGE'},
    /* 0x66 */ {'instruction': 'ROR', 'cycle': 5, 'addressing': 'ZERO_PAGE'},
    /* 0x67 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0x68 */ {'instruction': 'PLA', 'cycle': 4, 'addressing': 'IMPLIED'},
    /* 0x69 */ {'instruction': 'ADC', 'cycle': 2, 'addressing': 'IMMEDIATE'},
    /* 0x6A */ {'instruction': 'ROR', 'cycle': 2, 'addressing': 'ACCUMULATOR'},
    /* 0x6B */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x6C */ {'instruction': 'JMP', 'cycle': 0, 'addressing': 'INDIRECT'},
    /* 0x6D */ {'instruction': 'ADC', 'cycle': 4, 'addressing': 'ABSOLUTE'},
    /* 0x6E */ {'instruction': 'ROR', 'cycle': 6, 'addressing': 'ABSOLUTE'},
    /* 0x6F */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0x70 */ {'instruction': 'BVS', 'cycle': 2, 'addressing': 'RELATIVE'},
    /* 0x71 */ {'instruction': 'ADC', 'cycle': 5, 'addressing': 'INDEXED_INDIRECT_Y'},
    /* 0x72 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x73 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x74 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x75 */ {'instruction': 'ADC', 'cycle': 4, 'addressing': 'INDEXED_ZERO_PAGE_X'},
    /* 0x76 */ {'instruction': 'ROR', 'cycle': 6, 'addressing': 'INDEXED_ZERO_PAGE_X'},
    /* 0x77 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0x78 */ {'instruction': 'SEI', 'cycle': 2, 'addressing': 'IMPLIED'},
    /* 0x79 */ {'instruction': 'ADC', 'cycle': 4, 'addressing': 'INDEXED_ABSOLUTE_Y'},
    /* 0x7A */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x7B */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x7C */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x7D */ {'instruction': 'ADC', 'cycle': 4, 'addressing': 'INDEXED_ABSOLUTE_X'},
    /* 0x7E */ {'instruction': 'ROR', 'cycle': 7, 'addressing': 'INDEXED_ABSOLUTE_X'},
    /* 0x7F */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0x80 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x81 */ {'instruction': 'STA', 'cycle': 6, 'addressing': 'INDEXED_INDIRECT_X'},
    /* 0x82 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x83 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x84 */ {'instruction': 'STY', 'cycle': 3, 'addressing': 'ZERO_PAGE'},
    /* 0x85 */ {'instruction': 'STA', 'cycle': 3, 'addressing': 'ZERO_PAGE'},
    /* 0x86 */ {'instruction': 'STX', 'cycle': 3, 'addressing': 'ZERO_PAGE'},
    /* 0x87 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0x88 */ {'instruction': 'DEY', 'cycle': 2, 'addressing': 'IMPLIED'},
    /* 0x89 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x8A */ {'instruction': 'TXA', 'cycle': 2, 'addressing': 'IMPLIED'},
    /* 0x8B */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x8C */ {'instruction': 'STY', 'cycle': 4, 'addressing': 'ABSOLUTE'},
    /* 0x8D */ {'instruction': 'STA', 'cycle': 4, 'addressing': 'ABSOLUTE'},
    /* 0x8E */ {'instruction': 'STX', 'cycle': 4, 'addressing': 'ABSOLUTE'},
    /* 0x8F */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0x90 */ {'instruction': 'BCC', 'cycle': 2, 'addressing': 'RELATIVE'},
    /* 0x91 */ {'instruction': 'STA', 'cycle': 6, 'addressing': 'INDEXED_INDIRECT_Y'},
    /* 0x92 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x93 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x94 */ {'instruction': 'STY', 'cycle': 4, 'addressing': 'INDEXED_INDIRECT_Y'},
    /* 0x95 */ {'instruction': 'STA', 'cycle': 4, 'addressing': 'INDEXED_ZERO_PAGE_X'},
    /* 0x96 */ {'instruction': 'STX', 'cycle': 4, 'addressing': 'INDEXED_ZERO_PAGE_Y'},
    /* 0x97 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0x98 */ {'instruction': 'TYA', 'cycle': 2, 'addressing': 'IMPLIED'},
    /* 0x99 */ {'instruction': 'STA', 'cycle': 5, 'addressing': 'INDEXED_ABSOLUTE_Y'},
    /* 0x9A */ {'instruction': 'TXS', 'cycle': 2, 'addressing': 'IMPLIED'},
    /* 0x9B */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x9C */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x9D */ {'instruction': 'STA', 'cycle': 5, 'addressing': 'INDEXED_ABSOLUTE_X'},
    /* 0x9E */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0x9F */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0xA0 */ {'instruction': 'LDY', 'cycle': 2, 'addressing': 'IMMEDIATE'},
    /* 0xA1 */ {'instruction': 'LDA', 'cycle': 6, 'addressing': 'INDEXED_INDIRECT_X'},
    /* 0xA2 */ {'instruction': 'LDX', 'cycle': 2, 'addressing': 'IMMEDIATE'},
    /* 0xA3 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xA4 */ {'instruction': 'LDY', 'cycle': 3, 'addressing': 'ZERO_PAGE'},
    /* 0xA5 */ {'instruction': 'LDA', 'cycle': 3, 'addressing': 'ZERO_PAGE'},
    /* 0xA6 */ {'instruction': 'LDX', 'cycle': 3, 'addressing': 'ZERO_PAGE'},
    /* 0xA7 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0xA8 */ {'instruction': 'TAY', 'cycle': 2, 'addressing': 'IMPLIED'},
    /* 0xA9 */ {'instruction': 'LDA', 'cycle': 2, 'addressing': 'IMMEDIATE'},
    /* 0xAA */ {'instruction': 'TAX', 'cycle': 2, 'addressing': 'IMPLIED'},
    /* 0xAB */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xAC */ {'instruction': 'LDY', 'cycle': 4, 'addressing': 'ABSOLUTE'},
    /* 0xAD */ {'instruction': 'LDA', 'cycle': 4, 'addressing': 'ABSOLUTE'},
    /* 0xAE */ {'instruction': 'LDX', 'cycle': 4, 'addressing': 'ABSOLUTE'},
    /* 0xAF */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0xB0 */ {'instruction': 'BCS', 'cycle': 2, 'addressing': 'RELATIVE'},
    /* 0xB1 */ {'instruction': 'LDA', 'cycle': 5, 'addressing': 'INDEXED_INDIRECT_Y'},
    /* 0xB2 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xB3 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xB4 */ {'instruction': 'LDY', 'cycle': 4, 'addressing': 'INDEXED_ZERO_PAGE_X'},
    /* 0xB5 */ {'instruction': 'LDA', 'cycle': 4, 'addressing': 'INDEXED_ZERO_PAGE_X'},
    /* 0xB6 */ {'instruction': 'LDX', 'cycle': 4, 'addressing': 'INDEXED_ZERO_PAGE_Y'},
    /* 0xB7 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0xB8 */ {'instruction': 'CLV', 'cycle': 2, 'addressing': 'IMPLIED'},
    /* 0xB9 */ {'instruction': 'LDA', 'cycle': 4, 'addressing': 'INDEXED_ABSOLUTE_Y'},
    /* 0xBA */ {'instruction': 'TSX', 'cycle': 2, 'addressing': 'IMPLIED'},
    /* 0xBB */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xBC */ {'instruction': 'LDY', 'cycle': 4, 'addressing': 'INDEXED_ABSOLUTE_X'},
    /* 0xBD */ {'instruction': 'LDA', 'cycle': 4, 'addressing': 'INDEXED_ABSOLUTE_X'},
    /* 0xBE */ {'instruction': 'LDX', 'cycle': 4, 'addressing': 'INDEXED_ABSOLUTE_Y'},
    /* 0xBF */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0xC0 */ {'instruction': 'CPY', 'cycle': 2, 'addressing': 'IMMEDIATE'},
    /* 0xC1 */ {'instruction': 'CMP', 'cycle': 6, 'addressing': 'INDEXED_INDIRECT_X'},
    /* 0xC2 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xC3 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xC4 */ {'instruction': 'CPY', 'cycle': 3, 'addressing': 'ZERO_PAGE'},
    /* 0xC5 */ {'instruction': 'CMP', 'cycle': 3, 'addressing': 'ZERO_PAGE'},
    /* 0xC6 */ {'instruction': 'DEC', 'cycle': 5, 'addressing': 'ZERO_PAGE'},
    /* 0xC7 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0xC8 */ {'instruction': 'INY', 'cycle': 2, 'addressing': 'IMPLIED'},
    /* 0xC9 */ {'instruction': 'CMP', 'cycle': 2, 'addressing': 'IMMEDIATE'},
    /* 0xCA */ {'instruction': 'DEX', 'cycle': 2, 'addressing': 'IMPLIED'},
    /* 0xCB */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xCC */ {'instruction': 'CPY', 'cycle': 4, 'addressing': 'ABSOLUTE'},
    /* 0xCD */ {'instruction': 'CMP', 'cycle': 4, 'addressing': 'ABSOLUTE'},
    /* 0xCE */ {'instruction': 'DEC', 'cycle': 6, 'addressing': 'ABSOLUTE'},
    /* 0xCF */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0xD0 */ {'instruction': 'BNE', 'cycle': 2, 'addressing': 'RELATIVE'},
    /* 0xD1 */ {'instruction': 'CMP', 'cycle': 5, 'addressing': 'INDEXED_INDIRECT_Y'},
    /* 0xD2 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xD3 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xD4 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xD5 */ {'instruction': 'CMP', 'cycle': 4, 'addressing': 'INDEXED_ZERO_PAGE_X'},
    /* 0xD6 */ {'instruction': 'DEC', 'cycle': 6, 'addressing': 'INDEXED_ZERO_PAGE_X'},
    /* 0xD7 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0xD8 */ {'instruction': 'CLD', 'cycle': 2, 'addressing': 'IMPLIED'},
    /* 0xD9 */ {'instruction': 'CMP', 'cycle': 4, 'addressing': 'INDEXED_ABSOLUTE_Y'},
    /* 0xDA */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xDB */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xDC */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xDD */ {'instruction': 'CMP', 'cycle': 4, 'addressing': 'INDEXED_ABSOLUTE_X'},
    /* 0xDE */ {'instruction': 'DEC', 'cycle': 7, 'addressing': 'INDEXED_ABSOLUTE_X'},
    /* 0xDF */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0xE0 */ {'instruction': 'CPX', 'cycle': 2, 'addressing': 'IMMEDIATE'},
    /* 0xE1 */ {'instruction': 'SBC', 'cycle': 6, 'addressing': 'INDEXED_INDIRECT_X'},
    /* 0xE2 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xE3 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xE4 */ {'instruction': 'CPX', 'cycle': 3, 'addressing': 'ZERO_PAGE'},
    /* 0xE5 */ {'instruction': 'SBC', 'cycle': 3, 'addressing': 'ZERO_PAGE'},
    /* 0xE6 */ {'instruction': 'INC', 'cycle': 5, 'addressing': 'ZERO_PAGE'},
    /* 0xE7 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0xE8 */ {'instruction': 'INX', 'cycle': 2, 'addressing': 'IMPLIED'},
    /* 0xE9 */ {'instruction': 'SBC', 'cycle': 2, 'addressing': 'IMMEDIATE'},
    /* 0xEA */ {'instruction': 'NOP', 'cycle': 2, 'addressing': 'IMPLIED'},
    /* 0xEB */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xEC */ {'instruction': 'CPX', 'cycle': 4, 'addressing': 'ABSOLUTE'},
    /* 0xED */ {'instruction': 'SBC', 'cycle': 4, 'addressing': 'ABSOLUTE'},
    /* 0xEE */ {'instruction': 'INC', 'cycle': 6, 'addressing': 'ABSOLUTE'},
    /* 0xEF */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0xF0 */ {'instruction': 'BEQ', 'cycle': 2, 'addressing': 'RELATIVE'},
    /* 0xF1 */ {'instruction': 'SBC', 'cycle': 5, 'addressing': 'INDEXED_INDIRECT_Y'},
    /* 0xF2 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xF3 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xF4 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xF5 */ {'instruction': 'SBC', 'cycle': 4, 'addressing': 'INDEXED_ZERO_PAGE_X'},
    /* 0xF6 */ {'instruction': 'INC', 'cycle': 6, 'addressing': 'INDEXED_ZERO_PAGE_X'},
    /* 0xF7 */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},

    /* 0xF8 */ {'instruction': 'SED', 'cycle': 2, 'addressing': 'IMPLIED'},
    /* 0xF9 */ {'instruction': 'SBC', 'cycle': 4, 'addressing': 'INDEXED_ABSOLUTE_Y'},
    /* 0xFA */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xFB */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xFC */ {'instruction': 'INV', 'cycle': 0, 'addressing': null},
    /* 0xFD */ {'instruction': 'SBC', 'cycle': 4, 'addressing': 'INDEXED_ABSOLUTE_X'},
    /* 0xFE */ {'instruction': 'INC', 'cycle': 7, 'addressing': 'INDEXED_ABSOLUTE_X'},
    /* 0xFF */ {'instruction': 'INV', 'cycle': 0, 'addressing': null}
  ];

}
